Update gitignore and renames
LethalCompanyCommunity/LethalAPI.Monsters pull request #2
Opened 2023-11-28 16:43 UTC by Matthias1590

- Changed the .gitignore file to the appropriate version (Visual Studio project instead of a Unity project).
- Renamed the solution & project.

2023-11-28 19:18 UTC, MaxWasUnavailable requested changes
This uses a different format from Core. Needs to be reworked to use the original sln + csproj format.

2023-11-28 19:18 UTC, MaxWasUnavailable commented on LethalAPI.Monsters/LethalAPI.Monsters.csproj
This uses a different format from Core. Needs to be reworked to use the original sln + csproj format.

2023-11-28 19:18 UTC, MaxWasUnavailable commented on LethalAPI.Monsters/Properties/AssemblyInfo.cs
This uses a different format from Core. Needs to be reworked to use the original sln + csproj format.

2023-11-29 06:05 UTC, Redforce04 commented
Dang I just saw this after I made the same changes locally. Oh well

2023-11-29 16:39 UTC, closed without merging